version: '2'
services:
  db:
      image: mysql:8.0.26
      container_name: "drinks-db"
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
          - "3306:3306"
      environment:
          MYSQL_ROOT_PASSWORD: E4QWc8e7JJfdUZxvJ4#AyAVeBMv5Utjk

  site:
    container_name: "drinks-site"
    #    env_file:
    #  - ./.env
    image: mkosolofski/drinks-site:latest
    environment:
      NODE_ENV: "development"
      REACT_APP_DRINKS_API_URL: "http://api.drinks.com:8080"
    volumes:
      - ./Code/Site:/var/www/site
    ports:
        - "80:3000"
  
  api:
    image: mkosolofski/drinks-api:latest
    container_name: "drinks-api"
    volumes:
      - ./Code/Api:/var/www/Api
    ports:
        - "8080:80"
